#!/bin/bash

executable=nbody-p

if [ $1 == "help" ]; then
	echo "use BOTH    ./jrun both gpu N ts lwsg"
fi

if [ $1 == "both" ]; then
	plt=2
	dvc=$2
	N=$3
	ts=$4
	lwsg=$5
	#set the number of opencl device, and the device type
	export NX_OPENCL_MAX_DEVICES=1
	export NX_OPENCL_DEVICE_TYPE=GPU 
	#set the number of threads, vary ts to change nth 
	nth=`echo "scale=0; ${N} / ${ts}" | bc`  #get nth
	nthrmd=`echo "scale=0; ${N} % ${ts}" | bc`
	if [ ${nthrmd} -ne 0 ]; then
		nth=`echo "scale=0; ${nth} + 1" | bc`  #nth=nth+1 if remainder is not 0
	fi

	export NX_THREADS=${nth}

	export NX_SCHEDULE=versioning   #dp-perf
	#export NX_SCHEDULE=bf          #dp-dep	
	
	#printing the summary
	export NX_ARGS=--summary 	

	#run the program
	echo "[command ./${excutable} ${plt} ${N} ${ts} ${lwsg} (${nth} ${nthrmd})]"
	./${executable} ${plt} ${N} ${ts} ${lwsg}	
fi


